version: '3.8'

services:
  user-service:
    build: C:/auth-service
    container_name: auth-service
    ports:
      - "8080:8080"

  transaction-service:
    build: C:/user-service
    container_name: user-service
    ports:
      - "8081:8081"

  auth-service:
    build: C:/transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
